spring:

#  H2 DATABASE
#  Url de acceso a BBDD -> http://localhost:8080/h2-console/

  h2.console.enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:relog
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

#  SQL DATABASE
#  Se debe contar con un servidor MySQL local con una BBDD creada con el nombre "relog"

#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:mysql://localhost:3306/relog
#    username: root
#    platform: mssql
#    testWhileIdle: true
#    initialization-mode: always
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


